Create find_duplicates.py
CanCLID/rime-cantonese-upstream pull request #15
Opened 2022-06-04 03:42 UTC by AlienKevin

Finds all duplicated lines within the CSV files. Aims to close [issue 159](https://github.com/rime/rime-cantonese/issues/159) in [rime-cantonese](https://github.com/rime/rime-cantonese/issues/159)

2022-06-05 06:43 UTC, ayaka14732 requested changes
Thank you! You also need to modify the YAML files in `.github/workflows`.

2022-06-05 12:39 UTC, AlienKevin commented
@ayaka14732 I added `find_duplicates` to the workflows. Though I'm not sure about how the workflow actually runs. Currently, I changed the script to output error messages to stdout, like `validate.py`. There are 859 duplicated lines right now so my console is overflown when I run the script. You might need to redirect the messages to some log file for inspection.

2022-06-05 14:47 UTC, ayaka14732 commented
@AlienKevin If there exists duplicate entries in the dictionary, the script should terminate with a non-zero exit code, so that we will get a notification saying that the workflow run has failed.
@laubonghaudoi We should remove the duplicate entries first, then merge the changed dictionaries back to this branch.

2022-06-05 15:29 UTC, laubonghaudoi commented
@AlienKevin @ayaka14732 啱先刪咗重複詞條，你哋可以繼續嘞 https://github.com/CanCLID/rime-cantonese-upstream/commit/a80ee507406660331e6e7f9d0c79b0ef4db36ed5

2022-06-06 14:08 UTC, ayaka14732 commented
Why has the check passed? I thought https://github.com/CanCLID/rime-cantonese-upstream/commit/a80ee507406660331e6e7f9d0c79b0ef4db36ed5 has not been merged to this branch yet.

2022-06-06 15:25 UTC, laubonghaudoi commented
係唔係 @AlienKevin 已經將最新版 pull 咗落呢個 PR

2022-06-06 15:29 UTC, AlienKevin commented
呢個都幾奇怪，我冇pull過。會唔會checkout個action係自動checkout main分支嘅最新版本？

2022-06-06 15:36 UTC, ayaka14732 approved these changes
個 script 又好似冇咩問題

2022-06-06 17:06 UTC, ayaka14732 commented
> @ayaka14732 綾香你會唔會偏好用 `defaultdict`？

Oh, I didn't noticed. Should use `defaultdict` instead.

2022-06-06 19:39 UTC, AlienKevin commented
Didn't know `defaultdict` exists. Seems like a neat feature. Updated to use `defaultdict` instead of `dict`.

2022-06-06 23:29 UTC, graphemecluster commented
@AlienKevin You can pass the `list` constructor directly to the `defaultdict` constructor, I think it is the more common practice

2022-06-07 02:59 UTC, ayaka14732 requested changes

2022-06-07 02:59 UTC, ayaka14732 commented on scripts/find_duplicates.py
> +line_to_locations = defaultdict(lambda: [])
```suggestion
line_to_locations = defaultdict(list)
```

2022-06-07 02:59 UTC, ayaka14732 commented on scripts/find_duplicates.py
> +from collections import defaultdict
Sort imports:

```suggestion
from collections import defaultdict
from glob import iglob
import sys
```

2022-06-07 17:35 UTC, AlienKevin commented
@graphemecluster Got it. @ayaka14732 Just applied your suggestions as a new commit.

2022-07-11 16:49 UTC, merged