修復詞音
CanCLID/rime-cantonese-upstream pull request #19
Opened 2022-08-02 05:32 UTC by laubonghaudoi

2022-08-02 13:40 UTC, graphemecluster commented
要改 validate script 同我講

2022-08-11 06:35 UTC, laubonghaudoi commented
@graphemecluster 個validate script唔使改，但係個依賴庫 jyutping 好似要改，因為跑個check成日話 invalid jyutping，其實都係啱嘅，係唔係要 @ayaka14732 改先得？

2022-08-11 07:18 UTC, graphemecluster commented
@laubonghaudoi 我就係講緊粵拼庫個 validate script
https://github.com/CanCLID/python-jyutping/blob/rewrite/jyutping/validate.py

2022-08-12 05:39 UTC, laubonghaudoi commented
噉可唔可以將啲話係非法嘅音節都加返落去？

2022-08-23 08:27 UTC, graphemecluster commented on word.csv
> +噉冇嘢啦,gam2 mou5 je5 laa1
噉冇嘢喇

2022-08-23 08:27 UTC, graphemecluster commented on word.csv
> +通啦,tung1 laa1
（條渠）通喇？

2022-08-23 08:28 UTC, graphemecluster commented on word.csv
> +噉冇嘢啦,gam2 mou5 je5 laa1
laa3

2022-08-23 20:09 UTC, laubonghaudoi commented on word.csv
> +噉冇嘢啦,gam2 mou5 je5 laa1
你意思係想順便加多個詞條？好我下個commit加

2022-08-23 20:09 UTC, laubonghaudoi commented on word.csv
> +通啦,tung1 laa1
同上

2022-08-24 00:08 UTC, ayaka14732 commented on word.csv
> +噉冇嘢啦,gam2 mou5 je5 laa1
我覺得淨係可以講「噉冇嘢喇」

2022-08-24 14:50 UTC, graphemecluster commented on word.csv
> +噉冇嘢啦,gam2 mou5 je5 laa1
我覺得淨係可以講「噉冇嘢喇」

2022-08-24 23:25 UTC, laubonghaudoi commented on word.csv
> +噉冇嘢啦,gam2 mou5 je5 laa1
係咩，我覺得「噉冇嘢啦」同「噉冇嘢喇」係兩句唔同意思嘅話。「噉冇嘢啦」有啲隱含反問嘅意思

2023-04-07 18:10 UTC, ayaka14732 requested changes

2023-04-07 18:10 UTC, ayaka14732 commented on word.csv
> +打交叉,daa2 gaau1 caa1
daa2 kaau1 caa1 係啱嘅，兩種都有

2023-04-07 18:10 UTC, ayaka14732 commented on .vscode/settings.json
> +    "editor.fontSize": 12,
唔應該 set font size，del 咗佢就得

2023-04-07 18:13 UTC, laubonghaudoi commented on .vscode/settings.json
> +    "editor.fontSize": 12,
噉我乾脆成個刪晒，當初都唔知點解加咗入去

2023-04-07 18:30 UTC, ayaka14732 approved these changes

2023-04-07 20:13 UTC, graphemecluster commented on .vscode/settings.json
fontSize 當初係 Henry 加嘅，睇下佢意見先

2023-04-07 21:09 UTC, laubonghaudoi commented on .vscode/settings.json
好，噉你可唔可以 approve 先？

2023-04-09 00:11 UTC, merged

2023-04-09 00:40 UTC, graphemecluster commented on .vscode/settings.json
@hfhchan

2023-04-09 04:15 UTC, laubonghaudoi commented on .vscode/settings.json
如果佢覺得唔得嘅話之後再改

2023-04-09 07:40 UTC, hfhchan commented on .vscode/settings.json
加咗方便睇
啲字太細

2023-04-09 15:33 UTC, laubonghaudoi commented on .vscode/settings.json
我覺得喺我電腦度啲字太大，乾脆就噉刪咗佢，大家自己喺自己台電腦度定就得

2023-04-09 19:18 UTC, graphemecluster commented on .vscode/settings.json
噉一係加 `.vscode/settings.json` 落 `.gitignore` 度？

2023-04-10 02:01 UTC, ayaka14732 commented on .vscode/settings.json
係，大家自己喺自己台電腦度定就得