更改部分無法顯示嘅字
CanCLID/rime-cantonese-upstream pull request #2
Opened 2022-03-26 02:15 UTC by liujgoj

將一部份顯示為格仔嘅字，改為可以顯示嘅字。

2022-03-26 03:16 UTC, ayaka14732 commented
可唔可以講下你改咗啲乜嘢

2022-03-26 04:04 UTC, liujgoj commented
有幾個顯示為格仔嘅字，唔知係咩字。我將同一個發音下面嘅其他字（喺可以顯示嘅字入便冇嘅字），代替呢啲格仔。

2022-03-26 11:34 UTC, graphemecluster requested changes
Please remove all trailing commas.

2022-03-27 08:44 UTC, liujgoj commented
逗號係分隔符號，麻煩你睇睇，係唔係唔需要移除。

2022-04-02 08:58 UTC, graphemecluster approved these changes

2022-04-02 15:08 UTC, graphemecluster requested changes
Still problematic

2022-04-02 15:19 UTC, laubonghaudoi commented
而家呢個PR好似已經亂晒，我閂咗佢麻煩再凱歌新嘅

2022-04-02 15:19 UTC, closed without merging

2022-04-02 15:21 UTC, graphemecluster commented
不如直程叫人**刪**咗佢？